Geonovum/KP-APIs

- Werkgroep API strategie/Designrules v0.1.md
Verdere invulling van een aantal onderdelen op basis van de DSO API strategie, input uit discussies verwerkt. Synchronisatie met api principes.
> Update Designrules v0.1.md

- Bijlagen.md
Fixes issue #12 en #71 door de API principes 07 en 08 te verwijderen.
> Fixes issue #12 en #71

- Werkgroep API strategie/Designrules v0.1.md
> Fixes issues #12 en #71

- Werkgroep API strategie/Designrules v0.1.md
Fix voor de twee typo's in hoofdstuk 4 die genoemd worden in issue #78
> Fixes typos 1 en 2 uit issue #78

- Bijlagen.md
Fix typo zoals gemeld in issue #78
> Fix type uit issue #78

- Werkgroep API strategie/Designrules v0.1.md
Aanpassing van TLS 1.2 naar TLS 1.3 nav reviewopmerking Forum Standaardisatie. Fixes issue #80
> Fixes issue #80

- Werkgroep API strategie/Designrules v0.1.md
> Fixes issue #81

- Bijlagen.md
- Supplement.md
- Werkgroep API strategie/Designrules_en.md
Translated the Dutch text into English, changing the wording of the principles in active mode, avoiding negations).
> English translation

- API-strategie-extensies/ext-fouten.md
Zoals voorgesteld door werkgroep, zie https://github.com/Geonovum/KP-APIs/issues/21#issuecomment-467888849
> invalid-params vervangen door invalidParams

- API-strategie-extensies/config.js
- API-strategie-extensies/ext-beveiliging.md
Als besproken in de laatste werkgroepsessie van de API Security werkgroep (dd. 26 juni 2020) heb ik een voorzetje gemaakt voor de sectie "Authentication".
> Rewrite of Authentication section in Security chapter

- Werkgroep Design Visie/API Design Visie.md
Hoi Cathy,
De gevraagde aanpassingen zijn doorgevoerd. Als je rechts van het bestand op ... en dan `view file` klik, dan kan je een preview van de wijzigingen zien.
> Update API Design Visie.md

- API-strategie-extensies/ext-signing-encryptie.md
> JWT BCP is now RFC8725

- API-strategie-extensies/ext-beveiliging.md
Tekstvoorstel voor introductie in de extensie beveiliging, zoals afgelopen vrijdag in de werkgroep beveiliging besproken.
> Text proposal for introduction on security extension.

- API-strategie-extensies/ext-security.md
Update to HTTP level security intro.
> Added section on browser-based apps (SPA) and HTTP header filtering.

- API-strategie-extensies/ext-many-to-many-relations.md
Dit is het concept-resultaat van de werkgroep POST-PUT-PATCH-DELETE. Review is nog mogelijk.
> Extension voor many-to-many relations

- API-strategie-extensies/Summary v1.0.md
- API-strategie-extensies/ext-json.md
- API-strategie-extensies/ext-naming-conventions.md
Gerelateerd aan PR https://github.com/Geonovum/KP-APIs/pull/373
> Verwerking consultatiefeedback design rules extensies - naamgeving conventies

- Werkgroep API strategie en beleid/Werkversie/api-strategie-overheid.md
Verwoording eerste eenvoudige strategie: groeien en een concrete strategie uitwerken via Kennisplatform API's
> Update api-strategie-overheid.md eerste strategie

- API-strategie-extensies/ext-geospatial.md
> Added CRS discovery

- API-strategie-algemeen/config.js
- API-strategie-extensies/ext-geospatial.md
it makes more explicit that we only adopt the geometry aspect of geojson
it suggests to provide alternative geo oriented output formats
> suggestion for improvement #424

- API-strategie-extensies/ext-geospatial.md
API-36 verwijderd en een Note toegevoegd waarin staat dat filtering in een nieuwe extensie zal worden behandeld.
Closes #281
> Remove API-36 and add Note on filtering

- API-strategie-extensies/ext-geospatial.md
> add note about GeoJSON

- Werkgroep API strategie en beleid/Leden/Leden WG Strategie en Beleid.md
Mezelf toegevoegd als contactpersoon Logius
> Update Leden WG Strategie en Beleid.md

- API-strategie-modulen/Transport Security/Content.md
- API-strategie-modulen/Transport Security/Inleiding.md
- API-strategie-modulen/Transport Security/ext-security.md
- API-strategie-modulen/Transport Security/index.html
- API-strategie-modulen/Transport Security/js/config.js
- API-strategie-modulen/Transport Security/js/organisation-config.js
- API-strategie-modulen/Versioning/Content.md
- API-strategie-modulen/Versioning/Inleiding.md
- API-strategie-modulen/Versioning/LICENSE
- API-strategie-modulen/Versioning/README.md
- API-strategie-modulen/Versioning/abstract.md
- API-strategie-modulen/Versioning/ext-versioning.md
- API-strategie-modulen/Versioning/index.html
- API-strategie-modulen/Versioning/js/config.js
- API-strategie-modulen/Versioning/js/organisation-config.js
Modules security en versioning als aparte documenten.
> Development modulaire opbouw

- API-strategie-modulen/API-strategie-mod-geo/crs.md
- API-strategie-modulen/API-strategie-mod-geo/request-response.md
> Verduidelijkingen in hfd 2

- API-strategie-modulen/API-strategie-mod-geo/request-response.md
> Tekstaanpassing: module i.p.v extension

- API-strategie-modulen/API-strategie-mod-geo/request-response.md
> Rewrite intro for chapter 2 Request and Response

- API-strategie-modulen/API-strategie-mod-geo/crs.md
> Verduidelijking #494 en correctie nummering regels

- API-strategie-modulen/API-strategie-mod-geo/crs.md
move two implications of a rule into the rule box
Closes #492
> fix for #492

- API-strategie-modulen/API-strategie-mod-geo/request-response.md
> JSON API vervangen door REST API met JSON

- API-strategie-modulen/API-strategie-mod-geo/request-response.md
Een betere link voor de definitie van een collection heb ik niet kunnen vinden, hopelijk is deze goed genoeg.
Issue #497
> Link naar definitie van feature collection toegevoegd

- API-strategie-modulen/API-strategie-mod-geo/crs.md
> Add PUT/PATCH to GEO-API-11

- API-strategie-modulen/API-strategie-mod-geo/appendix.md
> Add API-36 and API-37 to appendix

- API-strategie-modulen/API-strategie-mod-geo/request-response.md
Een aantal voorbeelden uitgebreid met request URI incl. content-type.
> Voorbeelden uitbeiden

- API-strategie-modules/_template/index.html
- API-strategie-modules/hypermedia/LICENSE
- API-strategie-modules/hypermedia/README.md
- API-strategie-modules/hypermedia/abstract.md
- API-strategie-modules/hypermedia/hypermedia.md
- API-strategie-modules/hypermedia/index.html
- API-strategie-modules/hypermedia/js/config.js
- API-strategie-modules/naming-conventions/LICENSE
- API-strategie-modules/naming-conventions/README.md
- API-strategie-modules/naming-conventions/abstract.md
- API-strategie-modules/naming-conventions/index.html
- API-strategie-modules/naming-conventions/js/config.js
- API-strategie-modules/naming-conventions/naming-conventions.md
Ik heb de modules voor hypermedia en naming conventions toegevoegd.
> Add more modules

- API-strategie-modules/naming-conventions/naming-conventions.md
It's either lowerCamelCase or CamelCase.
> Possible typo

- overleggen/Werkgroep Notificeren/Notulen/Verslag 21-5-2025.md
> Update Verslag 21-5-2025.md
